# Run on port 8080 (default)
server.port=8080

# ===============================
# DATABASE CONFIGURATION (Firebase Only)
# ===============================

firebase.api.key=${FIREBASE_API_KEY:AIzaSyBwgvpebW4bbhcPsTybo-eWR7sbtA9eEm0}